name: test and tag

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --no-interaction

      - name: Execute tests
        run: vendor/bin/pest

  tag:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: none
          RELEASE_BRANCHES: main

    outputs:
      bump: ${{ steps.tag.outputs.part }}
      new_tag: ${{ steps.tag.outputs.new_tag }}

  build_release:
    runs-on: ubuntu-latest
    needs: tag
    if: needs.tag.outputs.bump
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Process changelog
        run: |
          if [[ ! -z $(cat changelog/next.md) ]] ; then
            mv changelog/next.md changelog/${{ needs.tag.outputs.new_tag }}.md
            touch changelog/next.md
          fi

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.email  "github@adminui.co.uk"
          git config --global user.name  "AdminUI Action"
          git add .
          git commit -m "Github Action compiled resources"
          git push

      - name: Set changelog path
        id: changelog_path
        run: |
          if [-e changelog/${TAG}.md]
          then
            echo "::set-output name=changelog::${TAG}"
          else
            echo "::set-output name=changelog::next"
          fi
        env:
          TAG: ${{ needs.tag.outputs.new_tag }}

      - name: Create Github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          release_name: Release ${{ needs.tag.outputs.new_tag }}
          body_path: changelog/${{ steps.changelog_path.outputs.changelog }}.md
          draft: false
          prerelease: false
